ShowScheduleEmailJob:                      # job 
   cron: "1 * * * * *"                                 # iteration of job  (every minute)
   class: "ShowEmailJob"                     # job to be perform every minute
